2018-01-20 13:54:13.015563 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 45, in run
    game_prx.login(player_prx, name)
AttributeError: 'NoneType' object has no attribute 'login'

2018-01-20 13:54:16.148579 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 45, in run
    game_prx.login(player_prx, name)
AttributeError: 'NoneType' object has no attribute 'login'

2018-01-20 23:02:29.217948 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-20 23:02:34.337180 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-20 23:04:20.160472 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-20 23:05:03.544328 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-21 04:01:42.163842 Player: warning: dispatch exception: src/Util.cpp:441: Ice::UnknownLocalException:
unknown local exception:
Traceback (most recent call last):
  File "./player.py", line 130, in makeController
    factory = robots.ControllerFactoryPrx.checkedCast(fact_prox)
  File "robots.ice", line 1048, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object adapter
    id = RCFactory0.FactoryAdapter
}

identity: 502C9A23-AAF3-4840-812C-6DE2E5AA1351
facet: 
operation: makeController
remote host: ::ffff:172.20.48.102 remote port: 58182
2018-01-21 04:03:29.891662 Player: warning: dispatch exception: src/Util.cpp:333: Ice::UnknownException:
unknown exception:
Traceback (most recent call last):
  File "./player.py", line 138, in makeController
    self.container.link(self.counter,rc,type)
  File "robots.ice", line 924, in link
ValueError: context argument must be None or a dictionary

identity: 07BCDB79-91D3-4E81-A0BD-45BB12AE9397
facet: 
operation: makeController
remote host: ::ffff:172.20.48.102 remote port: 53046
