2018-01-20 13:54:13.015563 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 45, in run
    game_prx.login(player_prx, name)
AttributeError: 'NoneType' object has no attribute 'login'

2018-01-20 13:54:16.148579 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 45, in run
    game_prx.login(player_prx, name)
AttributeError: 'NoneType' object has no attribute 'login'

2018-01-20 23:02:29.217948 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-20 23:02:34.337180 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-20 23:04:20.160472 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-20 23:05:03.544328 Player: error: Traceback (most recent call last):
  File "/home/alumno/.local/lib/python3.5/site-packages/Ice/__init__.py", line 1574, in doMain
    status = self.run(args)
  File "./player.py", line 25, in run
    game_prx = drobots.GamePrx.checkedCast(game_prx)
  File "robots.ice", line 801, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = drobots10
}

2018-01-21 03:26:07.611067 Player: warning: dispatch exception: src/Util.cpp:441: Ice::UnknownLocalException:
unknown local exception:
Traceback (most recent call last):
  File "./player.py", line 130, in makeController
    factory = robots.ControllerFactoryPrx.checkedCast(fact_prox)
  File "robots.ice", line 1048, in checkedCast
Ice.NotRegisteredException: exception ::Ice::NotRegisteredException
{
    kindOfObject = object
    id = factory0
}

identity: C10EAAEC-80DD-4175-B5A9-DB0CF74F8D3B
facet: 
operation: makeController
remote host: ::ffff:172.20.48.102 remote port: 47053
